#pragma once

#define KEY_MOVEMENT_FORWARD	'W'
#define KEY_MOVEMENT_BACKWARD	'S'
#define KEY_MOVEMENT_LEFT		'A'
#define KEY_MOVEMENT_RIGHT		'D'
#define KEY_ROTATION_LEFT		VK_LEFT
#define KEY_ROTATION_UP			VK_UP
#define KEY_ROTATION_RIGHT		VK_RIGHT
#define KEY_ROTATION_DOWN		VK_DOWN

enum GameStateMask
{
	STATE_LOADING,
	STATE_MAIN_MENU,
	STATE_IN_GAME,
	STATE_IN_GAME_MENU,
	STATE_OPTION,
	STATE_AUTHOR,
	STATE_HIGH_SCORE,
	STATE_LEVEL_COMPLETE,
	STATE_VICTORY,
	STATE_GAME_OVER,
	STATE_HELP
};

enum GameModelTypeMask
{
	MODEL_TYPE_OBJ,
	MODEL_TYPE_NFG
};

enum ListResourcesModelID
{
	PRIMARY_WEAPON_MODEL_ID = 8,
	BULLET_MODEL_ID = 9,
	BOX_MODEL_ID = 10,
	ROBOT_MODEL_ID = 11
};

enum ListResourcesTextureID
{
	PRIMARY_WEAPON_TEXTURE_ID = 14,
	BULLET_TEXTURE_ID = 15,
	HEALTH_BOX_TEXTURE_ID = 16,
	AMMO_BOX_TEXTURE_ID = 17,
	ROBOT_TEXTURE_ID = 18,
	FONT_COURIERNEW_TEXTURE_ID = 35,
	FONT_VINQUE_TEXTURE_ID = 36,
	FONT_BAI_SAU_TEXTURE_ID = 37
};

enum ListResourcesShaderID
{
	SHADER_3D_ID = 0,
	SHADER_TERRAIN_ID = 1,
	SHADER_CUBE_ID = 2,
	SHADER_ENVIRONMENT_REFLECTION_ID = 3,
	SHADER_FIRE_ID = 4,
	SHADER_PHONG_LINGHTING_ID = 5,
	SHADER_NORMAL_MAP_ID = 6,
	SHADER_WATER_ID = 7,
	SHADER_2D_ID = 8
};

enum BoxObjectType
{
	HEALTH_BOX,
	AMMO_BOX
};

enum KeyPressMask
{
	ESC_KEY = 27
};

enum KeyCameraMask
{
	KEY_MOVEMENT_FORWARD_MASK = 1 << 0,
	KEY_MOVEMENT_BACKWARD_MASK = 1 << 1,
	KEY_MOVEMENT_LEFT_MASK = 1 << 2,
	KEY_MOVEMENT_RIGHT_MASK = 1 << 3,
	KEY_ROTATION_LEFT_MASK = 1 << 4,
	KEY_ROTATION_UP_MASK = 1 << 5,
	KEY_ROTATION_RIGHT_MASK = 1 << 6,
	KEY_ROTATION_DOWN_MASK = 1 << 7
};
enum KeyEffectMask
{
	KEY_EFFECT_NONE = '0',
	KEY_EFFECT_BW = '1',
	KEY_EFFECT_BLUR = '2',
	KEY_EFFECT_BLOOM = '3',
	KEY_EFFECT_DOF = '4',
	KEY_EFFECT_EDGE_DETECTION = '5'
};
enum EffectMask
{
	EFFECT_NONE = -1,
	EFFECT_BW = 0,
	EFFECT_BLUR = 1,
	EFFECT_BLOOM = 2,
	EFFECT_DOF = 3,
	EFFECT_EDGE_DETECTION = 4
};